- conf/linz_bde_uploader.conf
- conf/tables.conf
Changes from old bde processor repository
> Version 2.0.4

- conf/linz_bde_uploader.conf
- conf/tables.conf
Reverts linz/linz_bde_uploader#37
> Revert "Version 2.0.4"

- conf/linz_bde_uploader.conf
- conf/tables.conf
@palmerj, can you confirm that this is how to do this?
> fixes #45 - Landonline 3.15 BDE changes

- bin/linz_bde_uploader.pl
> Fix typo in documentation

- bin/linz_bde_uploader.pl
> Fix -log-level documentation

- README.md
> Add proper quoting when appropriate, fix one **bold** usage

- bin/linz_bde_uploader.pl
> Clarify that -config-extension specifies an extension of -config-path

- sql/01-bde_control_tables.sql
.. simple one (let me know if you want me to push these directly)
> typo uninitiallized

- .gitignore
- .travis.yml
- MANIFEST
- bin/linz_bde_uploader.pl
- t/linz_bde_uploader.t
> Improve error reporting, automate tests for it

- .travis.yml
- debian/rules
Adds a travis step to test binary debian package building
> Test package building

- .travis.yml
- Build.PL
Hopefully exposes the issue reported in #48
> Build with Perl 5.26 too

- conf/linz_bde_uploader.conf
- lib/LINZ/BdeDatabase.pm
- t/linz_bde_uploader.t
Fixes duplicated stderr/logfile print on error.
Closes #75
Includes testcase.
> Do not print DBI errors, die already prints them

- t/linz_bde_uploader.t
And all errors related to missing directives.
See also #78
> Test minimal uploader configuration

- .travis.yml
- t/linz_bde_uploader.t
The README was missing instructions about creating the dbpatch
extension, while one of the files requires it (for no reason,
but it does).
See #83 for possible future changes
> Test database preparation, update README instructions about it

- README.md
- bin/linz_bde_uploader.pl
- lib/LINZ/BdeDatabase.pm
- lib/LINZ/BdeUpload.pm
- t/data/pab1.crs
- t/linz_bde_uploader.t
Code to deal with missing configuration was there, but it was
not working as expected by coder.
We want better default handling, see #78
> Fix handling of default configuration values

- .travis.yml
- lib/LINZ/BdeUpload.pm
- t/data/pab1.crs
- t/linz_bde_uploader.t
Upload actually fails, due to #90
> Install bde_copy and test a successul upload

- lib/LINZ/BdeDatabase.pm
> Add an hint in error message about "active" jobs to possibly be zombies

- bin/linz_bde_uploader.pl
- t/linz_bde_uploader.t
Fixes #103
Includes automated test
> Allow using an empty log_setting, considering it the same as missing

- sql/02-bde_control_functions.sql
> Add more INFO messages, to help with profiling operations

- sql/02-bde_control_functions.sql
To help with performance analisys via log reading
> Add progress NOTICEs in _bde_CopySchemaInformation

- lib/LINZ/BdeUpload.pm
- t/linz_bde_uploader.t
Allows defaulting to libpq defaults (PGAPPNAME) otherwise
See
https://github.com/linz/bde-processor-deployment/pull/40#issuecomment-316094905
> Only set application name if directive given in configuration

- bin/linz_bde_uploader.pl
- t/linz_bde_uploader.t
> Improve docs for -incremental and -full-incremental

- inc/MyBuilder.pm
- lib/LINZ/BdeDatabase.pm
- sql/02-bde_control_functions.sql.in
- t/linz_bde_uploader.t
Replaces $Id$ with git revision
Closes #111
> Expose GIT revision

- .travis.yml
Tests against PostgreSQL versions from 9.3 to 9.6
> Fix travis build, and test against more PostgreSQL and PostGIS versions

- sql/01-bde_control_tables.sql
Allows loading all sql scripts after contatenating them
> Add missing ending semicolon

- README.md
- bin/linz-bde-uploader-schema-load.pl
- inc/MyBuilder.pm
- t/linz_bde_uploader.t
> Add linz-bde-uploader-schema-load script

- bin/linz-bde-uploader-schema-load.pl
- sql/99-patches.sql
- t/linz_bde_uploader.t
> Add --noextension switch support to linz-bde-uploader-schema-load

- conf/linz_bde_uploader.conf
- conf/tables.conf
See: https://github.com/linz/linz_bde_uploader_private/commit/3ef0f023e6bcff63debaf8c8e7c1edc59e754296
> [linz_bde_uploader_private] LOL stopping updates of crs_map_grid

- lib/LINZ/BdeDatabase.pm
- lib/LINZ/BdeUpload.pm
- sql/02-bde_control_functions.sql.in
Allows loading to remote PostgreSQL server.
Closes #133
> Stream COPY data via stdin

- CHANGELOG.md
- lib/LINZ/BdeDatabase.pm
- lib/LINZ/BdeUpload.pm
- sql/02-bde_control_functions.sql.in
The function is unused since
https://github.com/linz/linz_bde_uploader/pull/134
> Drop the bde_UploadDataFromTempTable function

- sql/02-bde_control_functions.sql.in
Requires less privileges providing all the information we need
> Use pg_roles instead of pg_authid

- sql/01-bde_control_tables.sql
- sql/02-bde_control_functions.sql.in
- sql/99-patches.sql
Things like client_min_messages or search_path should not be
changed by enabling scripts
> Do not modify session loading enabling scripts

- bin/linz-bde-uploader-schema-load.pl
> Have linz-bde-uploader-schema-load cleanly exit on error

- bin/linz-bde-uploader-schema-load.pl
Makes linz-bde-uploader-schema-load less noisy
> Hush scripts loading

- CHANGELOG.md
- lib/LINZ/BdeUpload.pm
- t/linz_bde_uploader.t
> Do not exit with an error when no level0 datasets are available

- configure
> Add custom 'deb' rule

- debian/control
See https://github.com/linz/linz-bde-uploader/issues/171
> Update references to github repository

- .travis.yml
- CHANGELOG.md
- conf/tables.conf
- configure
- lib/LINZ/BdeUpload.pm
- sql/02-bde_control_functions.sql.in
- sql/99-patches.sql
- t/data/xaud.crs
- t/linz_bde_uploader.t
> Fix swapped inserts/deletes counts in upload stats

- .travis.yml
- CHANGELOG.md
- bin/linz-bde-uploader-schema-load.pl
- sql/99-patches.sql
- t/linz_bde_uploader.t
> Add stdout support to schema loader

- CHANGELOG.md
- sql/02-bde_control_functions.sql.in
- t/linz_bde_uploader.t
> Unversion versioned table before dropping it

- sql/02-bde_control_functions.sql.in
> Put the CASCADE back to the DROP TABLE in bde_ApplyLevel0Update

- CHANGELOG.md
> Fix release date for 2.5.0

- CHANGELOG.md
- t/linz_bde_uploader.t
> Fix test race condition

- .travis.yml
- debian/control
And allow depending on PostgreSQL-11 too for debian
> Test support for PostgreSQL-10

- .travis.yml
- CHANGELOG.md
- sql/02-bde_control_functions.sql.in
Prevents successfull full upload
> [2.5] Fix schema qualification for pg_sleep

- .travis.yml
- sql/02-bde_control_functions.sql.in
Prevents successfull full upload
> Fix schema qualification for pg_sleep

- CHANGELOG.md
- bin/linz_bde_uploader.pl
> Raise an error if -rebuild and --full-incremental are both given

- CHANGELOG.md
- lib/LINZ/BdeDatabase.pm
> Always include schema in calls to db functions

- sql/02-bde_control_functions.sql.in
INFO cannot be hidden by "client_min_messages" setting, NOTICE can
> Use NOTICE instead of INFO for progress messages

- .travis.yml
> [travis] Use bionic (18.04) ubuntu dist

- t/data/utf8.crs
- t/linz_bde_uploader.t
> Add test for uploading utf8 content

- conf/linz_bde_uploader.conf
- lib/LINZ/BdeUpload.pm
- t/linz_bde_uploader.t
This is what we want for proper upload of BDE files...
> Fix UTF8 handling

- .travis.yml
Copies .travis.yml from master branch
> [travis] Use bionic distribution

- CHANGELOG.md
- lib/LINZ/BdeDatabase.pm
- t/linz_bde_uploader.t
I think NOTICE are more informational messages than DEBUG ones...
> Map database NOTICE messages to log INFO instead of DEBUG

- conf/linz_bde_uploader.conf
- t/linz_bde_uploader.t
> Add tests for change-tolerated warnings in -full-incremental updates

- conf/tables.conf
- lib/LINZ/BdeDatabase.pm
- sql/02-bde_control_functions.sql.in
- sql/99-patches.sql
Stops relying on statistics, which was broken.
Fixes #229
> Refactor CheckTable count to receive change information

- CHANGELOG.md
- sql/02-bde_control_functions.sql.in
- sql/99-patches.sql
Replaces it with TRUNCATE/INSERT
Fixes #148, plays nicer with replication
> Avoid DROP TABLE when running full upload

- .github/workflows/test.yml
- .travis.yml
- CHANGELOG.md
- bin/linz-bde-uploader-schema-load.pl
- configure
- sql/01-bde_control_tables.sql
- t/schema.pg
- t/test-upgrades.sh
This PR is based on #240
Addresses #238
> Add --readonly switch to schema loader

- debian/control
> [debian] Make PostgreSQL server suggested, not required

- CHANGELOG.md
- sql/02-bde_control_functions.sql.in
I'm not sure this operation is "safe"
> Add NOTICE upon deleting unused revision

- .github/workflows/test.yml
- .travis.yml
- CHANGELOG.md
- lib/LINZ/BdeDatabase.pm
- sql/01-bde_control_tables.sql
- sql/02-bde_control_functions.sql.in
- t/linz_bde_uploader.t
Switches to `bde_admin` role as soon as it connects.
This is to test/prove that `bde_admin` role has enough privileges
to run the uploader.
> Always use `bde_admin` role during operations (and fixes to allow this)

- lib/LINZ/BdeUpload.pm
- t/linz_bde_uploader.t
Fixes #255
Includes automated testcase.
> Give a readable error on mismatch between BDE fields and col names
