linz/linz-bde-uploader

README.md

At the time of writing latest perl release is 5.26
Travis is testing from perl 5.12 to 5.24
Closes #64

Document perl requirement to be for 5.12+, not 5.88+

---

bin/linz_bde_uploader.pl
t/linz_bde_uploader.t

When -dry-run is specified, all logging configuration is already
replaced by a single configuration printing to console, this
change avoids adding another log Screen appender later.
Also, it changes the printing from stderr to stdout as that's what
is documented to be the destination for the similar -verbose switch.
Closes #59.
Includes testcase.
NOTE: replaces #60

Do not duplicate logs in -dry-run mode

---

README.md

Clarifies that linz-bde-schema is a required install,
and implications of setting it up with reguard to roles
and extensions.
Closes #85

Reword unix setup instructions

---

.travis.yml

As Travis already run the tests we know we have all dependencies,
just not installed the apt-way, no need to check

[travis] Do not install build dependencies for the sake of testing

---

README.md
conf/linz_bde_uploader.conf
lib/LINZ/BdeDatabase.pm
t/linz_bde_uploader.t

This is to remove an hard-coded high verbosity which makes
more noise than needed. With these changes it can be configured,
and will default to TERSE.

Add support for db_error_level configuration variable

---

sql/01-bde_control_tables.sql

Description of some fields are still confusing to me,
but the PR can be improved with help from @palmerj.
In particular, it isn't clear to me the description of
row_tol_warning and row_tol_error (ratio of what?) and
there's a reference to a cbe_tables.tablekeycolumn column
which is not clear to me (where's that table?)

Improve readability of bde_control tables

---

sql/02-bde_control_functions.sql
t/linz_bde_uploader.t

For debugging purposes, users can add this configuration to set
the request to keep temporary schema, like the following:
```
db_upload_complete_sql <<EOT
SELECT bde_control.bde_SetOption({{id}},'keep_temp_schema','yes');
EOT
```
Includes automated test
See https://github.com/linz/linz-lds-bde-schema/issues/23

Allow keeping temporary schema via `keep_temp_schema` option

---

sql/02-bde_control_functions.sql.in

Stable and IMMUTABLE function marks give planner useful hints
for improving performances.

Review IMMUTABLE/STABLE/VOLATILE status of each function

---

.travis.yml
README.md

From linz_bde_perl to linz-bde-perl
From linz_bde_copy to linz-bde-copy

Update references to linz-bde-{copy,perl} after repo rename

---

conf/linz_bde_uploader.conf
conf/tables.conf

The authoritative data source moved elsewhere, document it
in the tables.conf file.
See #39

Remove crs_statist_area from default list of uploaded tables

---

sql/02-bde_control_functions.sql.in

Restores function and ownership.
Fixes accidental drop of bde.bde_get_app_specific.
Closes #146
NOTE: lacks automated testing (as all functions in this schema)

Implement _bde_GetDependentObjectSql for dependent functions

---

debian/control

This patch is dropping hardcoded dependency on PgSQL 9.3 packages. Now as PgSQL 9.3 became unsupported it started to create bigger problems during deployment.

[debian] Remove hardcoded dependency on PgSQL 9.3 packages (support 9.3-9.6)

---

conf/linz_bde_uploader.conf

I don't think we read `bde_admin@linz.govt.nz`

Setting correct default log email in linz_bde_uploader.conf

---

CHANGELOG.md
lib/LINZ/BdeUpload.pm
sql/02-bde_control_functions.sql.in

specify that schema name must NOT be provided as it is derived
from upload identifier.
Includes CHANGELOG entry
Closes #173

Improve documentation of bde_TablesAffected

---

README.md

broken since rename of the repo from using underscores
to dashes..

Fix link to CI badge

---

.travis.yml

We still keep pre-stdout release branches to check that they still work

[travis] Also test release branches of dbpatch and tableversion

---

CHANGELOG.md
bin/linz_bde_uploader.pl
t/linz_bde_uploader.t

Fixes #204
Also make output consistent with using the same log format string
for empty log_setting, -v and -dry-run switches
NOTE: I personally find Filename:Number too verbose, but this is what
I ended up pushing consistency to...

Do not duplicate logs on stdout on empty log_setting and -v switch

---

CHANGELOG.md
conf/linz_bde_uploader.conf

For a big single transaction it shouldn't help much, and using
the LOCAL keyword was making it a no-op anyway (beside raising
a warning).
See #219

Do not set synchronous_commit off anymore

---

CHANGELOG.md
lib/LINZ/BdeUpload.pm
sql/02-bde_control_functions.sql.in
t/linz_bde_uploader.t

- Run table changes analysis on level 5 updates (#221)
- Provide default values for starttime warn/fail (#225)

Improve level5 check warnings/failres

---

.github/workflows/test.yml
README.md

At this stage the "test" workflow only tests
tableversion/dbpatch from packagecloud. This is
different from Travis which was testing 2 branches
(master and another) of each of the packages.
It has to be said that the "stable branches" tested by
Travis are a bit old at this moment.

Draft github actions workflow

---

CHANGELOG.md
sql/01-bde_control_tables.sql

Sets permissions at once at end of schema creation
Re-creates lost tables and indexes
Will also restore lost/changed permissions on schema elements

Still run DDL queries when bde_control schema exists

---

README.md
conf/linz_bde_uploader.conf

We really only need `bde_admin`, and actually we switch to that
account from within code, as soon as possible.

Fix config and dox pretending to use `bde_dba` instead of `bde_admin`

---

lib/LINZ/BdeDatabase.pm
sql/01-bde_control_tables.sql

Helps when a database is not prepared via schema-loader but rather
created by restoring a dump of a prepared database.

Grant bde_admin privileges at runtime rather than schema-creation time

---

.github/workflows/test.yml
debian/control

If Recommended `postgresql-X.Y-tableversion` package would be installed it would try to override files (like loader script) in `tableversion` which would fail. So has to be alternative `tableversion` or `postgresql-X.Y-tableversion`. Can't be both

[debian] Fix dependency on tableversion

---

sql/01-bde_control_tables.sql

Broken with 04afc706f9bfce57baea3823106ac57ca20e48f8
See #256
(CI is not checking PG93 so this has to be added, if we care)

Restore PG93 compatibility

---

CHANGELOG.md
bin/linz-bde-uploader-schema-load.pl

Presence of spurious BEGIN/COMMIT lines from tableversion and dbpatch
loaders resulted in multiple transactions occurring during load of
the bde-uploader schema.
Closes #267
It would be useful to secure a test for this!

Restore transactionality during loader

---

debian/control

We need a new table in LOL-3.22b for the default configuration to work

[debian] Encode dependency on linz-bde-schema 1.11.0+

---

.github/workflows/test.yml

We *want* to know whether the different builds fail for different
reasons.

feat: Don't fail fast

---

debian/control

We're always installing the latest version anyway, and manually setting
each version to the one we're testing against is too much work, so we
might as well remove the specifiers.

chore: Untether Debian control versions
